#!/usr/bin/perl

# Usage: Just like grep (mostly)
# 
# Will grep the file provided, along with any other files included/required by the file
# Supposed to work with PHP, probably doesn't cover every include keyword.
# Currently only supports one file being passed, at the end, everything else considered an
# argument to grep.
#
# Example:
# $ grep -c "DB_NAME" index.php
# 0
# $ grep_includes -l "DB_NAME" index.php
# Scripts/sql/inc.sql.php

use warnings;
use strict;
use Cwd;

exit if @ARGV < 2;

my $cwd = getcwd();
my $file = pop(@ARGV);

system ("grep " . join(' ',@ARGV,keys %{{get_includes($file)}}));

sub get_includes {
    my ($file, %includes) = @_;
    open my $input, "<", $file or return;
    local $/ = '';
    my $php = <$input>;
    close $input;
    my @php = split /;|\n/, $php;
    foreach my $line (@php) {
        if ($line =~ /(?:require(?:_once)?|include)(?:\s|\()('|")([^\1]+)\1/) {
            my $next_file = $2;
            next if $includes{$next_file};
            $includes{$next_file}++;
            %includes = get_includes($next_file, %includes);
        }
    }
    return %includes;
}
